### ISSUE TITLE
Missing Tinq icon

### ISSUE THREAD

**Issue by TASSDevon** [myTselection/Carbu_com#11]
The icon for the TinQ fuel station is missing --> https://www.tinq.be

**Comment by TASSDevon** [comment]
It seems to be an encoding issue:

IMG src from the carbu.com site: https://carbucomstatic-5141.kxcdn.com/brandLogo/326_Capture%20d%E2%80%99%C3%A9cran%202021-09-27%20%C3%A0%2011.11.24.png

IMG src in HA: https://carbucomstatic-5141.kxcdn.com/brandLogo/326_Capture%20d%C3%A2%C2%80%C2%99%C3%A9cran%202021-09-27%20%C3%A0%2011.11.24.png

Why they didn't properly rename the file rather than using a screenshot name from MacOS...

**Comment by myTselection** [comment]
I have tried many different solutions to encode this url, but still it was not working. For now, I have hard-coded the tinq logo, I didn't find any other solution so far and lost a lot of time on it...
