### ISSUE TITLE
Not possible to distinguish between areas with the same postal code

### ISSUE THREAD

**Issue by TASSDevon** [myTselection/Carbu_com#12]
On carbu.com website you can enter a city/village by name, which will yield the correct result. In the integration it's not the case always.

E.g. imagine you live in Vissenaken (3300), a deelgemeente of Tienen, there is currently no way to get results for this location as it will take Tienen.

I believe at the moment it just takes whatever result comes first in the list, V comes after T, so you're out of luck ;-)

**Comment by myTselection** [comment]
should be fixed as of v2.0.0
