### ISSUE TITLE
ValueError: could not convert string to float: ''

### ISSUE THREAD

**Issue by rob1998** [myTselection/Carbu_com#13]
Location "Lanaken" is not working properly. Upon inspecting I'm guessing it's using the wrong location ID (https://carbu.com//commonFunctions/getlocation/controller.getlocation_JSON.php?location=3620&SHRT=1)
BE_li_635 comes before BE_li_636 (the correct one) here, and the first one gets picked.
Maybe make both postal code and location ID required or at least configurable during setup to prevent this? While adding some documentation on how to find it ofc.

Logger: homeassistant.helpers.entity
Source: custom_components/carbu_com/sensor.py:440
Integration: Carbu.com ([documentation](https://github.com/myTselection/carbu_com), [issues](https://github.com/myTselection/carbu_com/issues))
First occurred: 15:16:01 (4 occurrences)
Last logged: 15:16:01

Update for sensor.carbu_com_super95_3620_5km fails
Update for sensor.carbu_com_super95_3620_10km fails
Update for sensor.carbu_com_diesel_3620_5km fails
Update for sensor.carbu_com_diesel_3620_10km fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/carbu_com/sensor.py", line 440, in async_update
    localPrice = float(self._priceinfo[0].get("price"))
ValueError: could not convert string to float: ''

**Comment by rob1998** [comment]
Overlaps with #12

**Comment by myTselection** [comment]
should be fixed now, tested myself with 3620 for different cases
