### ISSUE TITLE
Filter suppliers

### ISSUE THREAD

**Issue by stijnpiron** [myTselection/Carbu_com#15]
It would be nice to have an option to pass in suppliers you want/don't want to be included in the search query

**Comment by myTselection** [comment]
fixed since v2.2.0

**Comment by sammyke007** [comment]
@myTselection , hoe ziet de waarde van deze filter er bv uit voor ESSO en Q8? Gewoon "Esso, Q8" ?

**Comment by stijnpiron** [comment]
> @myTselection , hoe ziet de waarde van deze filter er bv uit voor ESSO en Q8? Gewoon "Esso, Q8" ?

`texaco|shell|total|q8|esso` works for me as far as I can tell, also seems not to be case sensitive, but not 100% sure.
Maybe some documentation can be added to clarify this? 🙂

**Comment by stijnpiron** [comment]
not sure if it is by coincidence, but without the ^, it seems to be working for me as well, since I've set the filter, I didn't get any other station suggestions, although I can see them when searching on the carbu website.
So for me, it feels like the filter is case insensitive and no limited to the exact values.

@myTselection can you confirm the way the filtering is working?

**Comment by myTselection** [comment]
Hi, indeed it's made case insensitive:
lowercase filter is applied as a python regex on lowercase supplier brand name to find matches.
So I would expect texaco|shell|total|q8|esso and ^Esso|^Q8 would both work

**Comment by stijnpiron** [comment]
> Hi, indeed it's made case insensitive: lowercase filter is applied as a python regex on lowercase supplier brand name to find matches. So I would expect texaco|shell|total|q8|esso and ^Esso|^Q8 would both work

And does the filter tries to match the explicit option or not?
I assume not as with my filter `texaco|shell|total|q8|esso` returns options like: 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/2921903/233601033-d62272b0-0390-4126-b4cc-0cd31722b77a.png">

correct?

**Comment by myTselection** [comment]
"|" in regex is an OR, so it matches with texaco or shell or total or q8 or esso
as soon as a match is found, the station will be selected.
