### ISSUE TITLE
Showing a Fuelstation +30km away as the locale cheapest

### ISSUE THREAD

**Issue by BelgianGuyWithALaser** [myTselection/Carbu_com#19]
Hi,

I've set this up for my current hometown (3650) and then it works perfect. yet for our new town (3960 Bree) it shows a fuelstation +30km away as the "cheapest local"
![Bree fuel](https://user-images.githubusercontent.com/75617571/233590865-54dcf7ce-f892-4039-80c8-1ef3fb0bec5b.png)
here is the Carbu link for the Bocken NV station so you can see the adress : https://carbu.com/belgie/index.php/station/vrijlibre/maasmechelen/3630/2216

Would there be any way to add a check that if it's + xx km's away (free to setup or so I suppose) it will not show up in the integration.

Kind regards,

Jordy

**Comment by myTselection** [comment]
I see different towns exist with postal code 3960. If only country and postal code are provided during setup, the first match will be selected (which would probably be 'Beek' for 3960). 
So you may try to remove the integration and set it up again with a 'Town' 'Bree'. I hope that would resolve this for you.

**Comment by BelgianGuyWithALaser** [comment]
sadly this does not resolve it. the postcode 3960 beek falls for "Bree" , that's how it's done here in Belgium (limburg) atleast. 
so that's still my town/commune. still doesn't explain the +30km difference to Maasmechelen. 
Also if that would have been an issue, my regular hometown one should also get different value's since under the postalcode of 3650 we have 5 towns (all under 3-5km from each other)

I've removed the integration, and added it with the town set to bree but then I get nothing at all as sensors. 
![Bree fuel2](https://user-images.githubusercontent.com/75617571/233614600-d2c86bfc-22bb-43c9-92b4-a78052e7c29c.png)

**Comment by BelgianGuyWithALaser** [comment]
Nvm, a force restart of my HA pulled in value's now. 
but the Bocken one should never popped up in my opinion.
I guess it's because of their pricing somehow? everything is it 0,00. So a distance check might still be a good option?

**Comment by myTselection** [comment]
true

**Comment by myTselection** [comment]
Analysed, but difficult to fully block. 
Yet, the setup flow has been updated in R4.0 to allow easy selection of the desired town if one postal code matches multiple towns. So this situation should probably no longer occur that easily.
If some town has no gas station, the closest available will be used. 
Will be closed for now.
