### ISSUE TITLE
fetch prices for selected stations

### ISSUE THREAD

**Issue by pcara** [myTselection/Carbu_com#24]
Thanks for this great integration!

Would it be possible to retrieve and display the price for one or two selected stations in home assistant?
I have a card for one brand (Total Energies) and two stations at about the same distance from my home. Their prices change often and sometimes show quite a nice difference...

Cheers,

Phil

**Comment by myTselection** [comment]
for a very specific station, you could use the scrape sensor as I originally used myself before creating this custom integration: https://community.home-assistant.io/t/dutch-gas-priceses/59230/70?u=myt

I'm still considering some integration of this, but this will require some advanced options in the config flow to setup the integration, currently not my top priority

**Comment by myTselection** [comment]
Hi, since R7.1.0 it will now be possible to select an individual gas station during setup of the entity. For now, only for gas stations in BE/FR/LU, over time I may also make it available for other countries NL/IT/DE.
