### ISSUE TITLE
Wrong postcode search

### ISSUE THREAD

**Issue by poudenes** [myTselection/Carbu_com#25]
Hi,

Great tool. I given my postcode 1082SG and Amsterdam. Those sensors are created:

sensor.carbu_com_super95_1082sg_10km
sensor.carbu_com_super95_1082sg_5km
sensor.carbu_com_super95_1082sg_price

But the name of sensors show this:

Carbu.com super95 1431WC 10km
Carbu.com super95 1431WC 5km
Carbu.com super95 1431WC price

1431WC is a total different postcode.

```
attribution: Carbu.com
last update: 2023-08-04T07:46:36.696720
fueltype: super95
fuelname: SUPER95
postalcode: 1431WC
supplier: Aalsmeer
supplier_brand: Tango
url: https://www.brandstof-zoeker.nl/station/tango-aalsmeer-2934
entity_picture: https://www.prezzibenzina.it/www2/marker.php?brand=TA&status=AP&price=2.009&certified=0&marker_type=1
address: Dreef 3
city: Aalsmeer
latitude: 52.256157
longitude: 4.765363
distance: 3.496622887109303km
date: 4 augustus 2023
quantity: 0
score: null
filter: 
country: NL
unit_of_measurement: €/l
device_class: monetary
icon: mdi:gas-station
friendly_name: Carbu.com super95 1431WC price
```

When I check brandstof zoeker then there are no hits on 1082SG. Maybe that is the issue? Better to make the sensor as: no info yet or something?

**Comment by poudenes** [comment]
Also postcode 1212VG / Hilversum gives a different result. When check the site it gives me correct location. Here result of sensor:

Postcode 3566ME is used.

```
attribution: Carbu.com
last update: 2023-08-04T07:47:15.340505
fueltype: super95
fuelname: SUPER95
postalcode: 3566ME
supplier: Iesberts
supplier_brand:   
url: https://www.brandstof-zoeker.nl/station/iesberts-utrecht-8972
entity_picture: https://www.prezzibenzina.it/www2/marker.php?brand=  &status=AP&price=1.999&certified=0&marker_type=1
address: Gageldijk 12
city: Utrecht
latitude: 52.11922
longitude: 5.126402
distance: 6.717660211582655km
date: 3 augustus 2023
quantity: 0
score: null
filter: 
country: NL
unit_of_measurement: €/l
device_class: monetary
icon: mdi:gas-station
friendly_name: Carbu.com super95 3566ME price
```

**Comment by myTselection** [comment]
Thanks for testing! I only tested a couple of locations so good to have some other test cases to validate :) I'll check what can be further improved.

**Comment by myTselection** [comment]
should be fixed in R7.0.3
the display name of the sensor changes according to the postalcode that is found in the region, the sensor name itself should keep the original postalcode of the input.

**Comment by poudenes** [comment]
Great. Will wait when HACS show me a update

**Comment by myTselection** [comment]
Hmm, the directlease scraping is extracting the fuel info out of an image. Looks rather cumbersome.
