### ISSUE TITLE
Cosmetic problem

### ISSUE THREAD

**Issue by poudenes** [myTselection/Carbu_com#26]
Hi,

Here a small cosmetic issue when add a new hub:

<img width="391" alt="Screenshot 2023-08-06 at 09 58 17" src="https://github.com/myTselection/Carbu_com/assets/4399532/29aac6d9-55c5-49fc-930f-30a2349fea55">

**Comment by myTselection** [comment]
the translation files have been updated. You may have to press F5 / Browser refresh to make sure the latest translation files are loaded
