### ISSUE TITLE
URL of 5km & 10km fuel station is NULL/Unknown

### ISSUE THREAD

**Issue by jonskoglund** [myTselection/Carbu_com#27]
There seems to be an issue in the way URL's are generated for fuelstations. See screenshots. Maybe only an NL issue?
When I go to Developer Tools>States and compare the attributes for 
- sensor.carbu_com_super95_3731_ge_10km
- sensor.carbu_com_super95_3731_ge_5km
- sensor.carbu_com_super95_3731_ge_price

Only the sensor ending with _price has a valid URL for the fuelstation. The other ones have null as URL.
In this situation the cheapest station for all the 3 sensors are one and the same. So all three should have the same URL 

<img width="350" alt="Screenshot 2023-08-06 at 10 40 29" src="https://github.com/myTselection/Carbu_com/assets/593324/38c8efcd-5e49-4e1f-8611-c9835c3fa6b3">
<img width="350" alt="Screenshot 2023-08-06 at 10 40 00" src="https://github.com/myTselection/Carbu_com/assets/593324/4ff328d4-843a-4b00-acbd-67a9254cd09c">
<img width="350" alt="Screenshot 2023-08-06 at 10 39 42" src="https://github.com/myTselection/Carbu_com/assets/593324/9f25516d-ad92-4982-89a9-52ec08e67e2f">

**Comment by myTselection** [comment]
just forgot to set the url apparently, thanks for reporting, fixed in 7.1.2
