### ISSUE TITLE
Station images corrupt?

### ISSUE THREAD

**Issue by LJStevo** [myTselection/Carbu_com#28]
(sorry for my amateur input)
Station image url is not what it should be?
entity_picture: https://www.prezzibenzina.it/www2/marker.php?brand=GA&status=AP&price=1.929&certified=0&marker_type=3

**Comment by myTselection** [comment]
Not all stations are known by this site. I'm (mis)using their icons to mostly get better icon's on the map with price indication. So I won't be able to fix this.

**Comment by LJStevo** [comment]
Strange, cause they worked before?

**Comment by myTselection** [comment]
They do still work, don't they?
Only for some brands the icon may be missing but price is still shown.
Or can you give more details on your issue?

**Comment by LJStevo** [comment]
Sorry for late reaction.
I think it's for all stations, for me atm "Maes" and "Avia"
Here a picture, also the fault in postal code 9100 showing Zwijndrecht instead of Sint-Niklaas
![afbeelding](https://github.com/myTselection/Carbu_com/assets/120583635/b13c9c2d-e350-4db5-b7a2-f10105ef530f)
![afbeelding](https://github.com/myTselection/Carbu_com/assets/120583635/b74e9862-d3b2-482f-88d4-93c70b40963c)

**Comment by myTselection** [comment]
I had changed the logo's, no longer using the logo's by carbu, but using instead the logo's of italian site. The benefit of the new logo's is that they can also immediately show the price, which i found usefull (eg on the map).
I might add an option in the config flow to allow you the select if the italian or carbu logo should be used

**Comment by myTselection** [comment]
Fixed in R7.3.0 with extra option during sensor setup
