### ISSUE TITLE
carbu_com does not generate unique IDs

### ISSUE THREAD

**Issue by tjorim** [myTselection/Carbu_com#3]
There should be a check in place to filter out existing places/postcoded.

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:540
Integration: Sensor (documentation, issues)
First occurred: 9:50:13 AM (1 occurrences)
Last logged: 9:50:13 AM

Platform carbu_com does not generate unique IDs. ID Carbu.com diesel 2470 price already exists - ignoring sensor.carbu_com_diesel_2470_price
```

**Comment by myTselection** [comment]
strange, as I tried to have the sensor name as unique as possible. How did you get to this error? Did you try to add the same postal code twice? When removing integration a reboot of HA might be required before adding again for the same postal code.

**Comment by tjorim** [comment]
Yes, I was adding some cities and forgot I already added 2470.
I think it should be possible for the integration to detect it was already set up.
Now it just sets it up, but without device or entity, only error logging.

**Comment by myTselection** [comment]
note to self: https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#unique-ids

**Comment by tjorim** [comment]
Also happening with the new price prediction for 2 different cities:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:540
Integration: Sensor (documentation, issues)
First occurred: 11:56:56 (4 occurrences)
Last logged: 12:04:04

Platform carbu_com does not generate unique IDs. ID Carbu.com diesel prediction already exists - ignoring sensor.carbu_com_diesel_prediction
```

**Comment by myTselection** [comment]
ok I see. But I guess it's best not to add these multiple times, since these sensors are not bound to a postalcode.
Will see if I can find a solution but I guess it's not blocking

**Comment by myTselection** [comment]
prediction sensor are not unique, others should be unique based on postal code. 
since prediction sensors are the same for any location, no need to re-create those with unique names
so for now I'd keep as is and close this issue
