### ISSUE TITLE
Can you ad LPG and Pellets to the type of fuel?

### ISSUE THREAD

**Issue by TimmieVL** [myTselection/Carbu_com#32]
Is there a way you can ad LPG and Pellets to the differnet type of fuels available?

**Comment by myTselection** [comment]
LPG would be an option I guess, not sure of which site to get pellets prices

**Comment by TimmieVL** [comment]
Lpg is fine.Tought carbu could also show pellet prices. But I was wrong. My mistake.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: myT ***@***.***> Datum: 7/09/2023  21:27  (GMT+01:00) Aan: myTselection/Carbu_com ***@***.***> Cc: TimmieVL ***@***.***>, Author ***@***.***> Onderwerp: Re: [myTselection/Carbu_com] Can you ad LPG and Pellets to the type of fuel? (Issue #32) 
LPG would be an option I guess, not sure of which site to get pellets prices

**Comment by myTselection** [comment]
added as of release 7.4.0
