### ISSUE TITLE
Integrate US gas station prices

### ISSUE THREAD

**Issue by myTselection** [myTselection/Carbu_com#33]
https://community.home-assistant.io/t/gas-pricing-plus-oil/286286/17 
[https://www.gasbuddy.com/ 1](https://www.gasbuddy.com/)

**Comment by myTselection** [comment]
has some protection to validate a human operator

**Comment by myTselection** [comment]
https://www.reddit.com/r/homeassistant/comments/xaairs/i_scraped_gasbuddy_so_i_know_how_much_my/

**Comment by pantherale0** [comment]
Hi @myTselection 

I didn't want to step on your shoes with what you have done here, but I had the same problem while building out my Python fuel prices library. Perhaps you can take some inspiration for this from https://github.com/pantherale0/pyfuelprices/blob/main/pyfuelprices/sources/usa/gasbuddy.py as it doesn't use the graphql endpoint / scraping.

**Comment by myTselection** [comment]
finally I found some time to integrate this. As of R10.0, first draft support for US gas stations is available. I have only performed some limited tests, so feel free to report issues.
