### ISSUE TITLE
Integrate Spanish gas station prices

### ISSUE THREAD

**Issue by myTselection** [myTselection/Carbu_com#34]
https://github.com/MiguelAngelLV/gas_station_spain/issues/3

**Comment by MiguelAngelLV** [comment]
Any question, I am here ;)

**Comment by myTselection** [comment]
First version release in R8.0. Only limited tests executed, I don't know many postalcodes in Spain ;)

**Comment by myTselection** [comment]
For now I retrieve all stations within a Provincia and calculated the approx distance to base location. 
So if a location is chosen close to bounderies of the provincia, it may not see all closeby gas stations as it will ignore other prvincia gas stations.
