### ISSUE TITLE
Add the official prices (today and tomorrow if available) ?

### ISSUE THREAD

**Issue by sammyke007** [myTselection/Carbu_com#37]
Hi

Is it possible to add the official prices in the integration please?

These:
https://carbu.com/belgie/super95
https://carbu.com/belgie/diesel

When the official price is going to change, there's an extra column available with the new upcoming price.

**Comment by myTselection** [comment]
thx for feedback and idea, I'll look into this in coming days/weeks

**Comment by sammyke007** [comment]
Ok, tnx! 
Just FYI, if you scrape the data from carbu, sometimes the column for the next day is available, but sometimes it isn't.

This morning:
![image](https://github.com/myTselection/Carbu_com/assets/33524412/8a98324a-8083-40d4-8cf4-a970a8162952)

Now:
![image](https://github.com/myTselection/Carbu_com/assets/33524412/daedc29f-42d7-4013-949f-1a05f6ac4891)

**Comment by myTselection** [comment]
Added in R9.0.0

**Comment by sammyke007** [comment]
And working great! Nice that the prices for tomorrow (if available) are attributes. Tnx!!
