### ISSUE TITLE
Only pulls in 1 station per postcode

### ISSUE THREAD

**Issue by tjorim** [myTselection/Carbu_com#4]
Setting up this integration only seems to set up a single device with a single entity.
Not sure if feature or bug.
I don't know what the logic here is: does it currently get the cheapest station, the first station in the list?
Feature request: would be nice if it adds all stations (entities) per postcode (device).

**Comment by myTselection** [comment]
for now, indeed the closet and cheapest is shown in the sensor, but internally all stations in the neighborhood are already retrieved. I plan to add extra sensors soon to also provide info on the cheapest station in the neighborhood of the postal code.
