### ISSUE TITLE
Platform carbu_com does not generate unique IDs

### ISSUE THREAD

**Issue by Sarnog** [myTselection/Carbu_com#40]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:610
Integration: Sensor (documentation, issues)
First occurred: 16:41:27 (2 occurrences)
Last logged: 16:41:27

 ID Carbu.com super95 prediction already exists - ignoring sensor.carbu_com_super95_prediction
Platform carbu_com does not generate unique IDs. ID Carbu.com super95 official e10 already exists - ignoring sensor.carbu_com_super95_official_e10

**Comment by myTselection** [comment]
I know, but I don't know immediately how to fix and I don't expect this has any further impact. I only want those sensors once else different sensor names would contain the same info repeated over multiple sensors.

**Comment by myTselection** [comment]
fixed in 11.2
