### ISSUE TITLE
Feature Request: Can we have a friendlier friendly_name?

### ISSUE THREAD

**Issue by RoelandPer** [myTselection/Carbu_com#41]
Installed your Custom Component after the provider for Skons "[dutch_gas_prices](![image](https://github.com/myTselection/Carbu_com/assets/155268682/f03ca842-6df8-4649-bc35-7525b23f5769))" apparently blocked access to their API.
Living literally on the border between Belgium and the Netherlands, I appreciate very much your components allows to query both sides of the border.
What I really liked about Skons' solution was that it allowed to create a "friendly_name"  using any attribute returned in the sensor.
See Skons' [DOCS.md](https://github.com/skons/hassio-addons/blob/ec3b1ea1bbee6996bcc3cc30135b95d1a4901fce/dutch_gas_prices/DOCS.md#friendly-name) for more information.

Thanks for the great work

**Edit:**  I may have been shooting faster than my shadow .... blame it on being a newbie around here.  Found [this article](https://community.home-assistant.io/t/customizing-entities-changing-friendly-names/189411) in HA Configuration .... Would this be the way to provide a friendly name?

**Comment by myTselection** [comment]
Thx for the feedback!
I like the idea of a configurable `friendly_name`. I'll look into it in the coming days and keep you posted.

**Comment by myTselection** [comment]
I was looking into this.
But I notice different template will be required as different "types" of sensors are being defined:

- price sensors: price for specific fuel type at the chosen location
- neighborhood price sensors: price for specific fuel type in the neighborhood of the chosen location (eg 5km or 10km)
- prediction price sensors: predicted price in coming days, % of increase or decrement of price that is expected
- official price sensors: official price

**Comment by RoelandPer** [comment]
I do not know how other HA users use your integration.  To me the sensors for a chosen location, the prediction sensors and official price sensors appear being more "static" when it comes to displaying their values on a dashboard; e.g. the entity name of a chosen gas-station is a fixed choice and can easily be changed using a YAML "name" tag on the dashboard.  The neighborhood price sensors have names and addresses varying as prices change throughout the week.  My vote would be to direct your efforts just to the "neighborhood price sensors".  
I'm looking forward to the day I've grown my Python knowledge enough to offer you a hand coding the other ones.  I started with HA just a month ago and, some books on Python last week and just mastered the "elif" (just kidding), so don't be afraid I will be touching your stuff soon ...

**Comment by myTselection** [comment]
I've found some way to achieve this, see update readme for info.
