### ISSUE TITLE
Alert as maximum diesel prices in Belgium will change

### ISSUE THREAD

**Issue by koenraadhaedens** [myTselection/Carbu_com#43]
In the site https://carbu.com/belgie/index.php/diesel , you can see if the maximum price will change in the next 2 days. Can I also retrieve the information so that I can generate an alert if the diesel price is expected to rise in the coming days?

**Comment by myTselection** [comment]
Yes, a sensor called diesel_prediction should be available. This will indicate if the trend is going up or down in the coming days, so you can create some alerts based on this.

**Comment by jrspowers** [comment]
Hello, I want to use this sensor for Super 98, but I can’t find it when I try to set it up for my region.
