### ISSUE TITLE
Add official price for NL

### ISSUE THREAD

**Issue by FRvanderVeen** [myTselection/Carbu_com#47]
Your integration supports official price for BE/FR/LU. Is it possible to add it for The Netherlands also? You could find it here: https://www.brandstof-zoeker.nl/adviesprijzen/. You're already using that site for getting the prices per station.

**Comment by myTselection** [comment]
I was looking into this, but still a bit confused with the NL naming. Do you know maybe?
"Diesel" and "Spec Diesel": which matches Diesel B7, B10, XTL
Euro 95, "Spec Benzine", "Super plus": which matches with E10, Super 98 E5, Super 98 E10.

**Comment by tjorim** [comment]
The 'diesel' is normal b7 diesel. Spec diesel are the premium brands with additives (https://www.unitedconsumers.com/tanken/informatie/brandstof-prijzen/premium-diesels). (The source of the prices on brandstof-zoeker.nl is actually unitedconsumers.com.)

The whole benzine situation seems more confusing and less/differently regulated or something. Euro 95 = 95 E10, clear. Super (plus) = 98 E5, clear. But the spec. benzine or premium benzine is not clear, it seems to be 98 but not always (indicated as) E10?

**Comment by FRvanderVeen** [comment]
The spec. benzine are the premium brands with additives (https://www.unitedconsumers.com/tanken/informatie/brandstof-prijzen/premium-benzines).
To me it looks like they are all 98 E5, but then with additives. I think there is no such a thing as 'Euro 98 / E10' in NL.

**Comment by myTselection** [comment]
great, thanks for the feedback! I'll try to integrate the official prices for nl in coming days

**Comment by myTselection** [comment]
added in 11.2
