### ISSUE TITLE
Oilextra 500L price entity unavalaible

### ISSUE THREAD

**Issue by LioBoul** [myTselection/Carbu_com#52]
Since one week, théle entity is unavalaible.
I have reinstall the intégration but still the same.

**Comment by myTselection** [comment]
Hi, just tested myself with some random BE location, seems to work still, eg getting https://mazout.com/belgie/offers?areaCode=BE_nm_1391&by=quantity&for=500&productId=2
For which location did you try?
I'm releasing a major new version v11.x, but no real changes expected on this part...

**Comment by LioBoul** [comment]
For 6640 but now it's OK.

![IMG_0413](https://github.com/user-attachments/assets/2221d9bc-b205-4572-ba7b-679da1a5e4f4)

**Comment by LioBoul** [comment]
Problem again :-(

![IMG_0441](https://github.com/user-attachments/assets/c28dfc65-2f79-487a-82ab-45fd119277be)

**Comment by myTselection** [comment]
I've found some issue with the oil standard prediction (the oil standard name and productID changed on the mazout.com website). But I don't think this is really related to your issue. I did setup the same sensor and seems to be working well in my test environment.

**Comment by myTselection** [comment]
I notice now the sensor had no value anymore, but after checking, this is because there is no data available on mazout.com for this location. So it seems on regular base no prices are known.
https://mazout.com/belgie/offers?areaCode=BE_lu_1714&by=quantity&for=500&productId=10
![image](https://github.com/user-attachments/assets/1ae4c051-eb90-4deb-9d83-19c7fae507e7)

So I will close this ticket as other locations are working well

**Comment by LioBoul** [comment]
I tried with 3 different localisations. Entity unavalaible 😔
![IMG_0601](https://github.com/user-attachments/assets/b49c4494-b8de-4eb8-8082-e9cc2a00ee51)
![IMG_0602](https://github.com/user-attachments/assets/6dc6eeb1-f93e-4f1c-b66e-9bd17b73cc6d)
![IMG_0603](https://github.com/user-attachments/assets/304c7be8-d198-416b-8f6d-4711332b65fa)
![IMG_0604](https://github.com/user-attachments/assets/854b757e-61f8-49a8-93a0-336c12c2fd61)

**Comment by LioBoul** [comment]
Brussel, same issue!
![IMG_0605](https://github.com/user-attachments/assets/fbda3ec8-d6b9-42f4-b712-240c1821b28b)
