### ISSUE TITLE
sensor.carbu_com_diesel_prediction  unavailable

### ISSUE THREAD

**Issue by Petch91** [myTselection/Carbu_com#58]
Hello,

I'm encountering a bug with the Carbu.com integration in Home Assistant. The sensor sensor.carbu_com_diesel_prediction is unavailable, and I'm getting a message saying it's no longer provided by the integration. Could you please confirm if this is normal or if there’s a fix for it?

Thank you!
![image](https://github.com/user-attachments/assets/c80cee1f-c9b2-49ea-88de-1d1cc9575560)

**Comment by myTselection** [comment]
could you try to delete and re-add the location in carbu? when adding a new sensor, it will check if the sensor 'sensor.carbu_com_diesel_prediction' already exists for another carbu location and won't add it again (as this will trigger an error of duplicate name). But if later on you'd remove the location having this prediction sensor, you could end up having it nowhere anymore.
