### ISSUE TITLE
Cosmetic request: colors change of icons

### ISSUE THREAD

**Issue by poudenes** [myTselection/Carbu_com#60]
Hi All,

I don't know if this is correct. I think the lowest price will be in green, the highest price in red.
Here its the other way around:
<img width="484" alt="Screenshot 2024-10-12 at 11 30 04" src="https://github.com/user-attachments/assets/fe1e88da-25e7-453b-af20-dcc09df05ce1">

Or does this mean. Red to see the alert or what ever: He this one is the cheapest !!! haha

**Comment by myTselection** [comment]
It's based on distance, green is the  closest,red is the furthest

**Comment by poudenes** [comment]
> It's based on distance, green is the closest,red is the furthest

Make sense :)

**Comment by poudenes** [comment]
Hey,

Based on my postalcode. This is not correct. The red one is closer then the green one...

<img width="480" alt="Screenshot 2024-10-13 at 17 36 16" src="https://github.com/user-attachments/assets/ce09e48a-971e-4264-bedb-083c6944e6bb">

**Comment by myTselection** [comment]
distance is based on distance to the provided postalcode/city, so this might not always be to a specific coordinate. 
The sensor has attributes indicating the distance

**Comment by poudenes** [comment]
I used postalcode/city: 1183 ZZ , Amstelveen
the postalcode is from a gas station itself haha, to check if I got the gas station in the list...
